# Generated by Django 3.2.8 on 2021-10-11 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='snippet',
            options={'ordering': ['-created_on']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='snippet',
            old_name='hits',
            new_name='visits',
        ),
    ]
