# Generated by Django 3.2.8 on 2021-10-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default='16346482595086906'),
        ),
    ]
