# Generated by Django 3.2.8 on 2021-10-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0003_alter_snippet_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default='1634652309253744'),
        ),
    ]
