# Generated by Django 3.2.8 on 2021-10-19 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0004_auto_20211019_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(default='16346523793103597', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='slug',
            field=models.SlugField(default='16346523793103597'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='16346523793103597', max_length=200, unique=True),
        ),
    ]
