# Generated by Django 3.2.8 on 2021-10-15 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangobin', '0005_auto_20211015_0905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
    ]
